# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tweets.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(963, 820)
        self.searchBtn = QtWidgets.QPushButton(Dialog)
        self.searchBtn.setGeometry(QtCore.QRect(795, 530, 95, 45))
        self.searchBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.searchBtn.setAutoFillBackground(False)
        self.searchBtn.setStyleSheet("color: rgb(0, 0, 0)")
        self.searchBtn.setAutoDefault(True)
        self.searchBtn.setDefault(True)
        self.searchBtn.setFlat(False)
        self.searchBtn.setObjectName("searchBtn")
        self.cancelBtn = QtWidgets.QPushButton(Dialog)
        self.cancelBtn.setGeometry(QtCore.QRect(690, 530, 95, 45))
        self.cancelBtn.setStyleSheet("")
        self.cancelBtn.setObjectName("cancelBtn")
        self.outputTxtInput = QtWidgets.QTextEdit(Dialog)
        self.outputTxtInput.setEnabled(True)
        self.outputTxtInput.setGeometry(QtCore.QRect(510, 640, 381, 121))
        self.outputTxtInput.setAutoFillBackground(False)
        self.outputTxtInput.setFrameShape(QtWidgets.QFrame.Box)
        self.outputTxtInput.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outputTxtInput.setReadOnly(True)
        self.outputTxtInput.setObjectName("outputTxtInput")
        self.label_Words = QtWidgets.QLabel(Dialog)
        self.label_Words.setGeometry(QtCore.QRect(21, 121, 54, 22))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_Words.setFont(font)
        self.label_Words.setObjectName("label_Words")
        self.lbl_anyofthesewords = QtWidgets.QLabel(Dialog)
        self.lbl_anyofthesewords.setGeometry(QtCore.QRect(20, 228, 131, 20))
        self.lbl_anyofthesewords.setObjectName("lbl_anyofthesewords")
        self.lbl_noneofthesewords = QtWidgets.QLabel(Dialog)
        self.lbl_noneofthesewords.setGeometry(QtCore.QRect(20, 259, 131, 20))
        self.lbl_noneofthesewords.setObjectName("lbl_noneofthesewords")
        self.lbl_thesehashtags = QtWidgets.QLabel(Dialog)
        self.lbl_thesehashtags.setGeometry(QtCore.QRect(20, 290, 141, 20))
        self.lbl_thesehashtags.setObjectName("lbl_thesehashtags")
        self.input_anyofthesewords = QtWidgets.QLineEdit(Dialog)
        self.input_anyofthesewords.setGeometry(QtCore.QRect(170, 228, 270, 21))
        self.input_anyofthesewords.setText("")
        self.input_anyofthesewords.setObjectName("input_anyofthesewords")
        self.input_noneofthesewords = QtWidgets.QLineEdit(Dialog)
        self.input_noneofthesewords.setGeometry(QtCore.QRect(170, 259, 270, 21))
        self.input_noneofthesewords.setText("")
        self.input_noneofthesewords.setObjectName("input_noneofthesewords")
        self.input_thesehashtags = QtWidgets.QLineEdit(Dialog)
        self.input_thesehashtags.setGeometry(QtCore.QRect(170, 290, 270, 21))
        self.input_thesehashtags.setText("")
        self.input_thesehashtags.setObjectName("input_thesehashtags")
        self.lbl_writtenin = QtWidgets.QLabel(Dialog)
        self.lbl_writtenin.setGeometry(QtCore.QRect(20, 321, 131, 20))
        self.lbl_writtenin.setObjectName("lbl_writtenin")
        self.input_writtenin = QtWidgets.QComboBox(Dialog)
        self.input_writtenin.setEnabled(True)
        self.input_writtenin.setGeometry(QtCore.QRect(170, 319, 164, 26))
        self.input_writtenin.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.input_writtenin.setFrame(True)
        self.input_writtenin.setObjectName("input_writtenin")
        self.input_writtenin.setObjectName("input_writtenin")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")       
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.input_writtenin.addItem("")
        self.label_Dates = QtWidgets.QLabel(Dialog)
        self.label_Dates.setGeometry(QtCore.QRect(21, 623, 48, 22))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_Dates.setFont(font)
        self.label_Dates.setObjectName("label_Dates")
        self.label_People = QtWidgets.QLabel(Dialog)
        self.label_People.setEnabled(True)
        self.label_People.setGeometry(QtCore.QRect(21, 371, 56, 22))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_People.setFont(font)
        self.label_People.setObjectName("label_People")
        self.input_fromtheseaccounts = QtWidgets.QLineEdit(Dialog)
        self.input_fromtheseaccounts.setEnabled(True)
        self.input_fromtheseaccounts.setGeometry(QtCore.QRect(170, 410, 270, 21))
        self.input_fromtheseaccounts.setObjectName("input_fromtheseaccounts")
        self.lbl_totheseaccounts = QtWidgets.QLabel(Dialog)
        self.lbl_totheseaccounts.setEnabled(True)
        self.lbl_totheseaccounts.setGeometry(QtCore.QRect(20, 439, 113, 16))
        self.lbl_totheseaccounts.setObjectName("lbl_totheseaccounts")
        self.lbl_mentioningtheseaccount = QtWidgets.QLabel(Dialog)
        self.lbl_mentioningtheseaccount.setEnabled(True)
        self.lbl_mentioningtheseaccount.setGeometry(QtCore.QRect(21, 472, 141, 31))
        self.lbl_mentioningtheseaccount.setScaledContents(False)
        self.lbl_mentioningtheseaccount.setWordWrap(True)
        self.lbl_mentioningtheseaccount.setObjectName("lbl_mentioningtheseaccount")
        self.input_totheseaccounts = QtWidgets.QLineEdit(Dialog)
        self.input_totheseaccounts.setEnabled(True)
        self.input_totheseaccounts.setGeometry(QtCore.QRect(169, 441, 270, 21))
        self.input_totheseaccounts.setText("")
        self.input_totheseaccounts.setObjectName("input_totheseaccounts")
        self.input_mentioningtheseaccounts = QtWidgets.QLineEdit(Dialog)
        self.input_mentioningtheseaccounts.setEnabled(True)
        self.input_mentioningtheseaccounts.setGeometry(QtCore.QRect(170, 472, 270, 21))
        self.input_mentioningtheseaccounts.setText("")
        self.input_mentioningtheseaccounts.setObjectName("input_mentioningtheseaccounts")
        self.lbl_fromtheseaccount = QtWidgets.QLabel(Dialog)
        self.lbl_fromtheseaccount.setEnabled(True)
        self.lbl_fromtheseaccount.setGeometry(QtCore.QRect(20, 409, 128, 16))
        self.lbl_fromtheseaccount.setObjectName("lbl_fromtheseaccount")
        self.label_Places = QtWidgets.QLabel(Dialog)
        self.label_Places.setEnabled(True)
        self.label_Places.setGeometry(QtCore.QRect(21, 531, 54, 22))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_Places.setFont(font)
        self.label_Places.setObjectName("label_Places")
        self.lbl_nearthisplace = QtWidgets.QLabel(Dialog)
        self.lbl_nearthisplace.setEnabled(True)
        self.lbl_nearthisplace.setGeometry(QtCore.QRect(20, 570, 151, 16))
        self.lbl_nearthisplace.setObjectName("lbl_nearthisplace")
        self.input_nearthisplace = QtWidgets.QLineEdit(Dialog)
        self.input_nearthisplace.setEnabled(True)
        self.input_nearthisplace.setGeometry(QtCore.QRect(170, 570, 270, 21))
        self.input_nearthisplace.setObjectName("input_nearthisplace")
        self.label_Export = QtWidgets.QLabel(Dialog)
        self.label_Export.setGeometry(QtCore.QRect(511, 121, 141, 22))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_Export.setFont(font)
        self.label_Export.setObjectName("label_Export")
        self.checkBox_getFollowersCount = QtWidgets.QCheckBox(Dialog)
        self.checkBox_getFollowersCount.setGeometry(QtCore.QRect(510, 360, 271, 21))
        self.checkBox_getFollowersCount.setFocusPolicy(QtCore.Qt.TabFocus)
        self.checkBox_getFollowersCount.setChecked(False)
        self.checkBox_getFollowersCount.setObjectName("checkBox_getFollowersCount")
        self.label_Output = QtWidgets.QLabel(Dialog)
        self.label_Output.setGeometry(QtCore.QRect(510, 600, 141, 22))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_Output.setFont(font)
        self.label_Output.setObjectName("label_Output")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(343, 40, 266, 27))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lbl_thisexactphrase = QtWidgets.QLabel(Dialog)
        self.lbl_thisexactphrase.setGeometry(QtCore.QRect(20, 197, 131, 20))
        self.lbl_thisexactphrase.setObjectName("lbl_thisexactphrase")
        self.input_allofthesewords = QtWidgets.QLineEdit(Dialog)
        self.input_allofthesewords.setGeometry(QtCore.QRect(170, 166, 270, 21))
        self.input_allofthesewords.setObjectName("input_allofthesewords")
        self.lbl_allofthesewords = QtWidgets.QLabel(Dialog)
        self.lbl_allofthesewords.setGeometry(QtCore.QRect(20, 166, 131, 20))
        self.lbl_allofthesewords.setObjectName("lbl_allofthesewords")
        self.input_thisexactphrase = QtWidgets.QLineEdit(Dialog)
        self.input_thisexactphrase.setGeometry(QtCore.QRect(170, 197, 270, 21))
        self.input_thisexactphrase.setText("")
        self.input_thisexactphrase.setObjectName("input_thisexactphrase")
        self.input_tothisdate = QtWidgets.QDateEdit(Dialog)
        self.input_tothisdate.setGeometry(QtCore.QRect(170, 723, 270, 31))
        self.input_tothisdate.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 7), QtCore.QTime(0, 0, 0)))
        self.input_tothisdate.setCalendarPopup(True)
        self.input_tothisdate.setObjectName("input_tothisdate")
        self.input_fromthisdate = QtWidgets.QDateEdit(Dialog)
        self.input_fromthisdate.setGeometry(QtCore.QRect(170, 663, 270, 31))
        self.input_fromthisdate.setCalendarPopup(True)
        self.input_fromthisdate.setObjectName("input_fromthisdate")
        self.lbl_fromthisdate = QtWidgets.QLabel(Dialog)
        self.lbl_fromthisdate.setGeometry(QtCore.QRect(20, 663, 88, 31))
        self.lbl_fromthisdate.setObjectName("lbl_fromthisdate")
        self.label_tothisdate = QtWidgets.QLabel(Dialog)
        self.label_tothisdate.setGeometry(QtCore.QRect(175, 700, 16, 16))
        self.label_tothisdate.setObjectName("label_tothisdate")
        self.input_filename = QtWidgets.QLineEdit(Dialog)
        self.input_filename.setGeometry(QtCore.QRect(615, 162, 270, 27))
        self.input_filename.setObjectName("input_filename")
        self.label_filename = QtWidgets.QLabel(Dialog)
        self.label_filename.setGeometry(QtCore.QRect(511, 162, 61, 27))
        self.label_filename.setObjectName("label_filename")
        self.label_exportfields = QtWidgets.QLabel(Dialog)
        self.label_exportfields.setGeometry(QtCore.QRect(510, 210, 81, 27))
        self.label_exportfields.setObjectName("label_exportfields")
        self.checkBox_getPermalink = QtWidgets.QCheckBox(Dialog)
        self.checkBox_getPermalink.setGeometry(QtCore.QRect(510, 240, 131, 21))
        self.checkBox_getPermalink.setFocusPolicy(QtCore.Qt.TabFocus)
        self.checkBox_getPermalink.setChecked(True)
        self.checkBox_getPermalink.setObjectName("checkBox_getPermalink")
        self.checkBox_getTweetDate = QtWidgets.QCheckBox(Dialog)
        self.checkBox_getTweetDate.setGeometry(QtCore.QRect(720, 270, 151, 21))
        self.checkBox_getTweetDate.setFocusPolicy(QtCore.Qt.TabFocus)
        self.checkBox_getTweetDate.setChecked(True)
        self.checkBox_getTweetDate.setObjectName("checkBox_getTweetDate")
        self.checkBox_getTweetDate.setEnabled(False)
        self.checkBox_getTweetPostersUsername = QtWidgets.QCheckBox(Dialog)
        self.checkBox_getTweetPostersUsername.setGeometry(QtCore.QRect(510, 270, 191, 21))
        self.checkBox_getTweetPostersUsername.setFocusPolicy(QtCore.Qt.TabFocus)
        self.checkBox_getTweetPostersUsername.setChecked(True)
        self.checkBox_getTweetPostersUsername.setObjectName("checkBox_getTweetPostersUsername")
        self.checkBox_getTweetPostersProfileName = QtWidgets.QCheckBox(Dialog)
        self.checkBox_getTweetPostersProfileName.setGeometry(QtCore.QRect(510, 300, 211, 21))
        self.checkBox_getTweetPostersProfileName.setFocusPolicy(QtCore.Qt.TabFocus)
        self.checkBox_getTweetPostersProfileName.setChecked(False)
        self.checkBox_getTweetPostersProfileName.setObjectName("checkBox_getTweetPostersProfileName")
        self.checkBox_getTweetText = QtWidgets.QCheckBox(Dialog)
        self.checkBox_getTweetText.setGeometry(QtCore.QRect(720, 300, 211, 21))
        self.checkBox_getTweetText.setFocusPolicy(QtCore.Qt.TabFocus)
        self.checkBox_getTweetText.setChecked(True)
        self.checkBox_getTweetText.setEnabled(False)
        self.checkBox_getTweetText.setObjectName("checkBox_getTweetText")
        self.checkBox_getTweetsNumberOfRetweets = QtWidgets.QCheckBox(Dialog)
        self.checkBox_getTweetsNumberOfRetweets.setGeometry(QtCore.QRect(510, 330, 201, 21))
        self.checkBox_getTweetsNumberOfRetweets.setFocusPolicy(QtCore.Qt.TabFocus)
        self.checkBox_getTweetsNumberOfRetweets.setChecked(True)
        self.checkBox_getTweetsNumberOfRetweets.setObjectName("checkBox_getTweetsNumberOfRetweets")
        self.checkBox_getTweetRetweetStatus = QtWidgets.QCheckBox(Dialog)
        self.checkBox_getTweetRetweetStatus.setGeometry(QtCore.QRect(720, 330, 211, 21))
        self.checkBox_getTweetRetweetStatus.setFocusPolicy(QtCore.Qt.TabFocus)
        self.checkBox_getTweetRetweetStatus.setChecked(True)
        self.checkBox_getTweetRetweetStatus.setObjectName("checkBox_getTweetRetweetStatus")
        self.checkBox_getTweetID = QtWidgets.QCheckBox(Dialog)
        self.checkBox_getTweetID.setGeometry(QtCore.QRect(720, 240, 91, 21))
        self.checkBox_getTweetID.setFocusPolicy(QtCore.Qt.TabFocus)
        self.checkBox_getTweetID.setChecked(True)
        self.checkBox_getTweetID.setEnabled(False)
        self.checkBox_getTweetID.setObjectName("checkBox_getTweetID")
        self.label_decreaseperformance = QtWidgets.QLabel(Dialog)
        self.label_decreaseperformance.setGeometry(QtCore.QRect(726, 390, 151, 27))
        self.label_decreaseperformance.setObjectName("label_decreaseperformance")
        self.checkBox_useProxy = QtWidgets.QCheckBox(Dialog)
        self.checkBox_useProxy.setEnabled(False)
        self.checkBox_useProxy.setGeometry(QtCore.QRect(510, 464, 91, 21))
        self.checkBox_useProxy.setChecked(False)
        self.checkBox_useProxy.setObjectName("checkBox_useProxy")
        self.input_proxyUrl = QtWidgets.QLineEdit(Dialog)
        self.input_proxyUrl.setEnabled(False)
        self.input_proxyUrl.setGeometry(QtCore.QRect(615, 460, 270, 27))
        self.input_proxyUrl.setObjectName("input_proxyUrl")
        self.label_Proxy = QtWidgets.QLabel(Dialog)
        self.label_Proxy.setGeometry(QtCore.QRect(510, 420, 141, 22))
        self.label_githubaccount = QtWidgets.QLabel(Dialog)
        self.label_githubaccount.setGeometry(QtCore.QRect(660, 790, 230, 16))
        self.label_githubaccount.setTextFormat(QtCore.Qt.RichText)
        self.label_githubaccount.setObjectName("label_githubaccount")
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_Proxy.setFont(font)
        self.label_Proxy.setObjectName("label_Proxy")
        self.lbl_anyofthesewords.setBuddy(self.input_anyofthesewords)
        self.lbl_noneofthesewords.setBuddy(self.input_noneofthesewords)
        self.lbl_thesehashtags.setBuddy(self.input_thesehashtags)
        self.lbl_writtenin.setBuddy(self.input_writtenin)
        self.lbl_totheseaccounts.setBuddy(self.input_totheseaccounts)
        self.lbl_mentioningtheseaccount.setBuddy(self.input_mentioningtheseaccounts)
        self.lbl_fromtheseaccount.setBuddy(self.input_fromtheseaccounts)
        self.lbl_nearthisplace.setBuddy(self.input_nearthisplace)
        self.lbl_thisexactphrase.setBuddy(self.input_thisexactphrase)
        self.lbl_allofthesewords.setBuddy(self.input_allofthesewords)
        self.lbl_fromthisdate.setBuddy(self.input_fromthisdate)
        self.label_tothisdate.setBuddy(self.input_tothisdate)
        self.label_filename.setBuddy(self.input_filename)
        self.label_exportfields.setBuddy(self.input_filename)
        self.label_decreaseperformance.setBuddy(self.input_filename)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.input_allofthesewords, self.input_thisexactphrase)
        Dialog.setTabOrder(self.input_thisexactphrase, self.input_anyofthesewords)
        Dialog.setTabOrder(self.input_anyofthesewords, self.input_noneofthesewords)
        Dialog.setTabOrder(self.input_noneofthesewords, self.input_thesehashtags)
        Dialog.setTabOrder(self.input_thesehashtags, self.input_writtenin)
        Dialog.setTabOrder(self.input_writtenin, self.input_fromtheseaccounts)
        Dialog.setTabOrder(self.input_fromtheseaccounts, self.input_totheseaccounts)
        Dialog.setTabOrder(self.input_totheseaccounts, self.input_mentioningtheseaccounts)
        Dialog.setTabOrder(self.input_mentioningtheseaccounts, self.input_nearthisplace)
        Dialog.setTabOrder(self.input_nearthisplace, self.input_fromthisdate)
        Dialog.setTabOrder(self.input_fromthisdate, self.input_tothisdate)
        Dialog.setTabOrder(self.input_tothisdate, self.input_filename)
        Dialog.setTabOrder(self.input_filename, self.checkBox_getPermalink)
        Dialog.setTabOrder(self.checkBox_getPermalink, self.checkBox_getTweetID)
        Dialog.setTabOrder(self.checkBox_getTweetID, self.checkBox_getTweetPostersUsername)
        Dialog.setTabOrder(self.checkBox_getTweetPostersUsername, self.checkBox_getTweetDate)
        Dialog.setTabOrder(self.checkBox_getTweetDate, self.checkBox_getTweetPostersProfileName)
        Dialog.setTabOrder(self.checkBox_getTweetPostersProfileName, self.checkBox_getTweetText)
        Dialog.setTabOrder(self.checkBox_getTweetText, self.checkBox_getTweetsNumberOfRetweets)
        Dialog.setTabOrder(self.checkBox_getTweetsNumberOfRetweets, self.checkBox_getTweetRetweetStatus)
        Dialog.setTabOrder(self.checkBox_getTweetRetweetStatus, self.checkBox_getFollowersCount)
        Dialog.setTabOrder(self.checkBox_getFollowersCount, self.checkBox_useProxy)
        Dialog.setTabOrder(self.checkBox_useProxy, self.input_proxyUrl)
        Dialog.setTabOrder(self.input_proxyUrl, self.cancelBtn)
        Dialog.setTabOrder(self.cancelBtn, self.searchBtn)
        Dialog.setTabOrder(self.searchBtn, self.outputTxtInput)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Twitter Advanced Search"))
        self.searchBtn.setText(_translate("Dialog", "Search"))
        self.cancelBtn.setText(_translate("Dialog", "Cancel"))
        self.label_Words.setText(_translate("Dialog", "Words"))
        self.lbl_anyofthesewords.setText(_translate("Dialog", "Any of these words"))
        self.lbl_noneofthesewords.setText(_translate("Dialog", "None of these words"))
        self.lbl_thesehashtags.setText(_translate("Dialog", "Any of these hashtags"))
        self.input_anyofthesewords.setToolTip(_translate("Dialog", "Example: cats dogs · contains either “cats” or “dogs” (or both)"))
        self.input_noneofthesewords.setToolTip(_translate("Dialog", "Example: cats dogs · does not contain “cats” and does not contain “dogs”"))
        self.input_thesehashtags.setToolTip(_translate("Dialog", "Example: #ThrowbackThursday · contains the hashtag #ThrowbackThursday"))
        self.lbl_writtenin.setText(_translate("Dialog", "Written in"))
        self.input_writtenin.setItemText(0,_translate("Dialog","Any language"))
        self.input_writtenin.setItemText(1,_translate("Dialog","Arabic"))
        self.input_writtenin.setItemText(2,_translate("Dialog","Bangla"))
        self.input_writtenin.setItemText(3,_translate("Dialog","Basque"))
        self.input_writtenin.setItemText(4,_translate("Dialog","Bulgarian"))
        self.input_writtenin.setItemText(5,_translate("Dialog","Catalan"))
        self.input_writtenin.setItemText(6,_translate("Dialog","Croatian"))
        self.input_writtenin.setItemText(7,_translate("Dialog","Czech"))
        self.input_writtenin.setItemText(8,_translate("Dialog","Danish"))
        self.input_writtenin.setItemText(9,_translate("Dialog","Dutch (Nederlands)"))
        self.input_writtenin.setItemText(10,_translate("Dialog","English"))
        self.input_writtenin.setItemText(11,_translate("Dialog","Finnish"))
        self.input_writtenin.setItemText(12,_translate("Dialog","French"))
        self.input_writtenin.setItemText(13,_translate("Dialog","German"))
        self.input_writtenin.setItemText(14,_translate("Dialog","Greek"))
        self.input_writtenin.setItemText(15,_translate("Dialog","Gujarati"))
        self.input_writtenin.setItemText(16,_translate("Dialog","Hebrew"))
        self.input_writtenin.setItemText(17,_translate("Dialog","Hindi"))
        self.input_writtenin.setItemText(18,_translate("Dialog","Hungarian"))
        self.input_writtenin.setItemText(19,_translate("Dialog","Indonesian"))
        self.input_writtenin.setItemText(20,_translate("Dialog","Italian"))
        self.input_writtenin.setItemText(21,_translate("Dialog","Japanese"))
        self.input_writtenin.setItemText(22,_translate("Dialog","Kannada"))
        self.input_writtenin.setItemText(23,_translate("Dialog","Korean"))
        self.input_writtenin.setItemText(24,_translate("Dialog","Marathi"))
        self.input_writtenin.setItemText(25,_translate("Dialog","Norwegian"))
        self.input_writtenin.setItemText(26,_translate("Dialog","Persian"))
        self.input_writtenin.setItemText(27,_translate("Dialog","Polish"))
        self.input_writtenin.setItemText(28,_translate("Dialog","Portuguese"))
        self.input_writtenin.setItemText(29,_translate("Dialog","Romanian"))
        self.input_writtenin.setItemText(30,_translate("Dialog","Russian"))
        self.input_writtenin.setItemText(31,_translate("Dialog","Serbian"))
        self.input_writtenin.setItemText(32,_translate("Dialog","Simplified Chinese"))
        self.input_writtenin.setItemText(33,_translate("Dialog","Slovak"))
        self.input_writtenin.setItemText(34,_translate("Dialog","Spanish"))
        self.input_writtenin.setItemText(35,_translate("Dialog","Swedish"))
        self.input_writtenin.setItemText(36,_translate("Dialog","Tamil"))
        self.input_writtenin.setItemText(37,_translate("Dialog","Thai"))
        self.input_writtenin.setItemText(38,_translate("Dialog","Traditional Chinese"))
        self.input_writtenin.setItemText(39,_translate("Dialog","Turkish"))
        self.input_writtenin.setItemText(40,_translate("Dialog","Ukrainian"))
        self.input_writtenin.setItemText(41,_translate("Dialog","Urdu"))
        self.input_writtenin.setItemText(42,_translate("Dialog","Vietnamese"))
        self.label_Dates.setText(_translate("Dialog", "Dates"))
        self.label_People.setText(_translate("Dialog", "People"))
        self.input_fromtheseaccounts.setToolTip(_translate("Dialog", "Example: @Twitter · sent from @Twitter"))
        self.lbl_totheseaccounts.setText(_translate("Dialog", "To these accounts"))
        self.lbl_mentioningtheseaccount.setText(_translate("Dialog", "Mentioning these accounts"))
        self.input_totheseaccounts.setToolTip(_translate("Dialog", "Example: @Twitter · sent in reply to @Twitter"))
        self.input_mentioningtheseaccounts.setToolTip(_translate("Dialog", "Example: @SFBART @Caltrain · mentions @SFBART or mentions @Caltrain"))
        self.lbl_fromtheseaccount.setText(_translate("Dialog", "From these accounts"))
        self.label_Places.setText(_translate("Dialog", "Places"))
        self.lbl_nearthisplace.setText(_translate("Dialog", "Near this place"))
        self.label_Export.setText(_translate("Dialog", "Export Options"))
        self.checkBox_getFollowersCount.setText(_translate("Dialog", "*Tweet\'s poster number of followers"))
        self.label_Output.setText(_translate("Dialog", "Export Progress"))
        self.label.setText(_translate("Dialog", "Twitter Advanced Search"))
        self.lbl_thisexactphrase.setText(_translate("Dialog", "This exact phrase"))
        self.input_allofthesewords.setToolTip(_translate("Dialog", "Example: what’s happening · contains both “what’s” and “happening”"))
        self.lbl_allofthesewords.setText(_translate("Dialog", "All of these words"))
        self.input_thisexactphrase.setToolTip(_translate("Dialog", "Example: happy hour · contains the exact phrase “happy hour”"))
        self.input_tothisdate.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd"))
        self.input_fromthisdate.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd"))
        self.lbl_fromthisdate.setText(_translate("Dialog", "From this date"))
        self.label_tothisdate.setText(_translate("Dialog", "to"))
        self.input_filename.setText(_translate("Dialog", "search-results.csv"))
        self.label_filename.setText(_translate("Dialog", "Filename"))
        self.label_exportfields.setText(_translate("Dialog", "Export fields"))
        self.checkBox_getPermalink.setText(_translate("Dialog", "Tweet\'s permalink"))
        self.checkBox_getTweetDate.setText(_translate("Dialog", "Tweet\'s posted date"))
        self.checkBox_getTweetPostersUsername.setText(_translate("Dialog", "Tweet\'s poster (Username)"))
        self.checkBox_getTweetPostersProfileName.setText(_translate("Dialog", "*Tweet\'s poster (Profile name)"))
        self.checkBox_getTweetText.setText(_translate("Dialog", "Tweet\'s text"))
        self.checkBox_getTweetsNumberOfRetweets.setText(_translate("Dialog", "Tweet\'s number of retweets"))
        self.checkBox_getTweetRetweetStatus.setText(_translate("Dialog", "Is a retweet status"))
        self.checkBox_getTweetID.setText(_translate("Dialog", "Tweet\'s ID"))
        self.label_decreaseperformance.setText(_translate("Dialog", "* Performance decrease"))
        self.checkBox_useProxy.setText(_translate("Dialog", "Use Proxy"))
        self.input_proxyUrl.setText(_translate("Dialog", "Proxy URL"))
        self.label_Proxy.setText(_translate("Dialog", "Proxy"))
        self.label_githubaccount.setText(_translate("Dialog", "<a href=\"https://github.com/yiannakasgeorge/\">https://github.com/yiannakasgeorge/</a> "))
        self.label.adjustSize()
        self.label_Output.adjustSize()
        self.label_Words.adjustSize()
        self.label_Export.adjustSize()
        self.label_Places.adjustSize()
        self.label_People.adjustSize()
        self.label_Dates.adjustSize()
        self.label_Proxy.adjustSize()
        self.label_githubaccount.adjustSize()
